name: ZekeJohnsonArt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7d7c7a'
    - '#1a0808'
    - '#9cd7f5'
    - '#ee7c62'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.3597706879954785
  rhythmicContrast: 0.75
purpose: []
