name: ZekeJohnsonArt
favicon: null
layout_spectrum: 0.06642341217957437
typography_spectrum: 0.8297417997382581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6231399087700993
  lightness: 0.8398406167980283
  saturation: 0.3597706879954785
  rhythmicContrast: 0.06413994822651148
purpose: []
